<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Karthiks-MacBook-Pro.local" failures="1" tests="5" name="LoginTest" time="30.412" errors="0" timestamp="2021-05-17T22:28:06 BST">
  <testcase classname="com.openMRS.tests.LoginTest" name="testInvalidLogin" time="3.77">
    <skipped/>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="com.openMRS.tests.LoginTest" name="testInvalidLogin" time="4.607">
    <skipped/>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="com.openMRS.tests.LoginTest" name="testInvalidLogin" time="2.212">
    <skipped/>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="com.openMRS.tests.LoginTest" name="testInvalidLogin" time="3.471">
    <failure type="java.lang.AssertionError" message="expected [My account - My Store] but found [Login - My Store]">
      <![CDATA[java.lang.AssertionError: expected [My account - My Store] but found [Login - My Store]
at com.openMRS.tests.LoginTest.testInvalidLogin(LoginTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="com.openMRS.tests.LoginTest" name="testValidLogin" time="4.868"/>
</testsuite> <!-- LoginTest -->
